name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: 'gradle'
    - name: Build & Test
      run: xvfb-run -a ./gradlew build

    - uses: actions/upload-artifact@v4
      with:
        name: Linux binaries
        path: build/libs
